using System.Text.Json;
using BlazecoinWallet.Lite.Data;

namespace BlazecoinWallet.Lite.Core.Tests;

/// <summary>
/// Phoenix-413 (Era 3) — the lite verifier's exact-target function must be BIT-EXACT
/// against the canonical vectors generated by test/phoenix413/generate_phoenix_vectors.py
/// in the V2 repo. The same file pins the V2 daemon's C++ and the V1.5.2 client's
/// OpenSSL-BN implementations; this is the cross-implementation consensus guarantee.
/// </summary>
public class Phoenix413Tests
{
    private sealed record Vector(string name, uint anchor_bits, long anchor_parent_time,
        long anchor_height, long eval_height, long parent_time, uint expect_bits);

    private static List<Vector> LoadVectors()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "phoenix413_vectors.json");
        using var doc = JsonDocument.Parse(File.ReadAllText(path));
        var list = new List<Vector>();
        foreach (var v in doc.RootElement.GetProperty("vectors").EnumerateArray())
        {
            list.Add(new Vector(
                v.GetProperty("name").GetString()!,
                v.GetProperty("anchor_bits").GetUInt32(),
                v.GetProperty("anchor_parent_time").GetInt64(),
                v.GetProperty("anchor_height").GetInt64(),
                v.GetProperty("eval_height").GetInt64(),
                v.GetProperty("parent_time").GetInt64(),
                v.GetProperty("expect_bits").GetUInt32()));
        }
        return list;
    }

    [Fact]
    public void All_canonical_vectors_match_bit_exactly()
    {
        var vectors = LoadVectors();
        Assert.True(vectors.Count >= 45, $"expected the full canonical set, got {vectors.Count}");
        foreach (var v in vectors)
        {
            var got = BlazecoinDifficulty.PhoenixNextBits(
                v.anchor_bits, v.anchor_parent_time, v.anchor_height, v.eval_height, v.parent_time);
            Assert.True(got == v.expect_bits,
                $"vector {v.name}: expected 0x{v.expect_bits:x8}, got 0x{got:x8}");
        }
    }

    [Fact]
    public void Activation_constants_match_the_ratified_fork()
    {
        // H_A chosen 2026-08-26 (PHOENIX_413.md); half-life is 413 blocks of 30 s.
        Assert.Equal(4_194_000, BlazecoinDifficulty.PhoenixActivationHeight);
        Assert.Equal(30, BlazecoinDifficulty.PhoenixTargetSpacing);
        Assert.Equal(12_390, BlazecoinDifficulty.PhoenixHalfLife);
        // The shipped checkpoint must sit BELOW H_A−1 so a fresh install's forward
        // sync passes through the fork and captures the anchor from real headers.
        Assert.True(HeaderChainSync.MainnetCheckpoint.Height < BlazecoinDifficulty.PhoenixActivationHeight - 1);
    }

    [Fact]
    public void Checkpoint_serialization_roundtrips_with_anchor_and_legacy_forms()
    {
        var full = new HeaderCheckpoint(4_194_100, new string('a', 64), 0x1c3a6a29,
            1787755148, 0x1c3a0000, 1787755000);
        var parsed = HeaderCheckpoint.TryParse(full.Serialize());
        Assert.Equal(full, parsed);

        // Legacy 3-part form (pre-Phoenix releases) still parses, with zeroed extras.
        var legacy = HeaderCheckpoint.TryParse($"4193000:{new string('b', 64)}:472934953");
        Assert.NotNull(legacy);
        Assert.Equal(0, legacy!.Time);
        Assert.Equal(0u, legacy.AnchorBits);
    }
}
