using System.Security.Cryptography;
using System.Text.Json;
using BlazecoinWallet.Lite.Pq;
using NBitcoin;
using NBitcoin.DataEncoders;

namespace BlazecoinWallet.Lite.Core.Tests;

/// <summary>
/// P2PQH / PQSigHash (PQ_SIGNATURES.md) — the lite wallet's post-quantum primitives must be
/// BIT-EXACT against the canonical vectors generated by contrib/pqsig/generate_pqsig_vectors.py
/// in the V2 repo (a pure-Python FIPS 204 implementation, independent of both the daemon's
/// vendored C and this project's BouncyCastle). Same discipline as <see cref="Phoenix413Tests"/>:
/// the vectors are the semantic authority; where a reading of the spec and a vector disagree,
/// the vector wins and the spec text is the thing to fix.
/// </summary>
public class PqSignaturesTests
{
    private static readonly Lazy<JsonDocument> Doc = new(() =>
        JsonDocument.Parse(File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "pqsig_vectors.json"))));

    private static JsonElement Root => Doc.Value.RootElement;

    /// <summary>The generator's fixture master seed (00 01 02 … 1f); keys[i] = Derive(master, i).</summary>
    private static readonly byte[] Master = Hex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f");

    /// <summary>keys[0..29], derived once (the generator uses 30: 0..28 as spenders, 29 as a payee).</summary>
    private static readonly Lazy<PqKey[]> Keys = new(() =>
        Enumerable.Range(0, 30).Select(i => PqKeyDerivation.Derive(Master, i)).ToArray());

    private static byte[] Hex(string s) => Encoders.Hex.DecodeData(s);
    private static string Hex(ReadOnlySpan<byte> b) => Encoders.Hex.EncodeData(b.ToArray());
    private static string Sha256Hex(byte[] b) => Hex(SHA256.HashData(b));

    private static Transaction ParseTx(string hex) => Transaction.Parse(hex, BlazecoinNetwork.Instance);

    // ── constants ─────────────────────────────────────────────────────────────────────────

    [Fact]
    public void Constants_match_the_vectors_and_the_spec()
    {
        var c = Root.GetProperty("constants");
        Assert.Equal(PqScript.AlgoIdMlDsa44, c.GetProperty("algo_id_mldsa44").GetByte());
        Assert.Equal(MlDsa44.PublicKeyLength, c.GetProperty("pubkey_len").GetInt32());
        Assert.Equal(MlDsa44.SecretKeyLength, c.GetProperty("seckey_len").GetInt32());
        Assert.Equal(MlDsa44.SignatureLength, c.GetProperty("sig_len").GetInt32());
        Assert.Equal(MlDsa44.SeedLength, c.GetProperty("seed_len").GetInt32());
        Assert.Equal(PqScript.OpCheckPqSig, c.GetProperty("op_checkpqsig").GetByte());
        Assert.Equal(TaggedHash.PqkhTag, c.GetProperty("tag_pqkh").GetString());
        Assert.Equal(TaggedHash.SigHashTag, c.GetProperty("tag_sighash").GetString());
        Assert.Equal(TaggedHash.SeedTag, c.GetProperty("tag_seed").GetString());
        Assert.Equal(MlDsa44.TxContext, c.GetProperty("ctx_tx").GetString());
        Assert.Equal(PqSigHash.SigHashAll, c.GetProperty("sighash_all").GetUInt32());
        Assert.Equal(c.GetProperty("address_prefix_main").GetString(), Hex(PqAddress.MainnetPrefix));
        Assert.Equal(c.GetProperty("address_prefix_test").GetString(), Hex(PqAddress.TestPrefix));
        Assert.Equal(PqScript.MaxElementSize, c.GetProperty("max_pq_element_size").GetInt32());
        Assert.Equal(PqScript.ScriptSigLength, c.GetProperty("scriptsig_len").GetInt32());
        Assert.Equal(PqScript.InputLength, c.GetProperty("input_len").GetInt32());
        Assert.Equal(3739, PqScript.ScriptSigLength);
        Assert.Equal(3782, PqScript.InputLength);
    }

    [Fact]
    public void Address_examples_from_the_spec_encode_and_decode()
    {
        var ex = Root.GetProperty("constants").GetProperty("address_examples");
        var zero = new byte[32];
        var ff = Enumerable.Repeat((byte)0xff, 32).ToArray();
        Assert.Equal(ex.GetProperty("pqkh_00").GetString(), PqAddress.Encode(zero));
        Assert.Equal(ex.GetProperty("pqkh_ff").GetString(), PqAddress.Encode(ff));
        Assert.Equal("BQGeaQmsowAjL1ZG8q1AfVH4NgBvtJKJSsjnnKEf62BMjekdU82n", PqAddress.Encode(zero));
        Assert.Equal("BQJbKb1KqnbQZ9NqqjanfSbf9bJYbx29KfNrtZPLz1qN89DPR4Hh", PqAddress.Encode(ff));

        // 52 characters, always "BQ…" on mainnet; decode round-trips; the codec refuses the rest.
        foreach (var kh in new[] { zero, ff })
        {
            var a = PqAddress.Encode(kh);
            Assert.Equal(PqAddress.Length, a.Length);
            Assert.StartsWith("BQ", a);
            Assert.True(PqAddress.IsValid(a));
            Assert.Equal(kh, PqAddress.Decode(a));
            Assert.Equal(PqScript.BuildP2pqh(kh), PqAddress.ToScriptPubKey(a));
            Assert.Equal(a, PqAddress.FromScriptPubKey(PqScript.BuildP2pqh(kh)));
        }
        Assert.False(PqAddress.IsValid("BQGeaQmsowAjL1ZG8q1AfVH4NgBvtJKJSsjnnKEf62BMjekdU82m")); // checksum
        Assert.False(PqAddress.IsValid(LiteHdWallet.Restore(TestMnemonic).GetReceiveAddress(0))); // legacy B…
        Assert.False(PqAddress.IsValid(null));
        Assert.False(PqAddress.IsValid(""));
        Assert.Null(PqAddress.TryDecode("BQ"));
    }

    [Fact]
    public void Tx26_serialized_length_is_pinned_under_the_standard_limit()
    {
        var expected = Root.GetProperty("constants").GetProperty("tx26_serialized_len").GetInt32();
        var tx26 = Root.GetProperty("sighash")[2];
        Assert.Equal(26, tx26.GetProperty("inputs").GetArrayLength());
        var bytes = Hex(tx26.GetProperty("tx").GetString()!);
        Assert.Equal(expected, bytes.Length);
        Assert.Equal(expected, ParseTx(tx26.GetProperty("tx").GetString()!).GetSerializedSize());
        Assert.True(expected <= PqScript.MaxStandardTxBytes);
        Assert.Equal(26, PqScript.MaxPqInputsPerStandardTx);
    }

    [Fact]
    public void Activation_height_is_H_Q()
    {
        // H_Q = 4,250,000 chosen 2026-09-15 (PQ_SIGNATURES.md s7/s15); this constant IS the lite fork.
        Assert.Equal(4_250_000L, BlazecoinChain.PqSigActivationHeight);
    }

    // ── derivation ────────────────────────────────────────────────────────────────────────

    [Fact]
    public void Every_derivation_vector_matches_bit_exactly()
    {
        var vectors = Root.GetProperty("derivation").EnumerateArray().ToList();
        Assert.Equal(3, vectors.Count);
        foreach (var v in vectors)
        {
            var i = v.GetProperty("index").GetInt32();
            Assert.Equal(Hex(Master), v.GetProperty("master_seed").GetString());
            var key = Keys.Value[i];

            Assert.Equal(v.GetProperty("xi").GetString(), Hex(key.Seed));
            Assert.Equal(v.GetProperty("xi").GetString(), Hex(PqKeyDerivation.KeySeed(Master, (uint)i)));
            Assert.Equal(v.GetProperty("pubkey").GetString(), Hex(key.PublicKey));
            Assert.Equal(v.GetProperty("seckey_sha256").GetString(), Sha256Hex(MlDsa44.KeyPairFromSeed(key.Seed).SecretKey));
            Assert.Equal(v.GetProperty("keyblob_sha256").GetString(), Sha256Hex(key.KeyBlob));
            Assert.Equal(v.GetProperty("pqkh").GetString(), Hex(key.KeyHash));
            Assert.Equal(v.GetProperty("scriptPubKey").GetString(), Hex(key.ScriptPubKey));
            Assert.Equal(v.GetProperty("address_main").GetString(), key.Address());
            Assert.Equal(v.GetProperty("address_main").GetString(), key.Address(BlazecoinNetwork.Instance));
            Assert.Equal(v.GetProperty("address_test").GetString(), key.Address(BlazecoinNetwork.Regtest));

            // The key blob is what a spend reveals; the sizes are consensus.
            Assert.Equal(PqScript.KeyBlobLength, key.KeyBlob.Length);
            Assert.Equal(PqScript.AlgoIdMlDsa44, key.KeyBlob[0]);
            Assert.Equal(PqScript.ScriptPubKeyLength, key.ScriptPubKey.Length);
            Assert.True(PqScript.IsP2pqh(key.ScriptPubKey));
        }
    }

    [Fact]
    public void Regtest_addresses_use_the_TQ_prefix_and_never_validate_on_mainnet()
    {
        foreach (var v in Root.GetProperty("derivation").EnumerateArray())
        {
            var test = v.GetProperty("address_test").GetString()!;
            var main = v.GetProperty("address_main").GetString()!;
            Assert.StartsWith("TQ", test);
            Assert.Equal(PqAddress.Length, test.Length);
            var decoded = PqAddress.TryDecode(test);
            Assert.NotNull(decoded);
            Assert.False(decoded.Value.Mainnet);
            Assert.Equal(Hex(v.GetProperty("pqkh").GetString()!), decoded.Value.KeyHash);
            Assert.True(PqAddress.IsValid(test, BlazecoinNetwork.Regtest));
            Assert.False(PqAddress.IsValid(test));                             // mainnet default refuses TQ
            Assert.False(PqAddress.IsValid(main, BlazecoinNetwork.Regtest));   // and regtest refuses BQ
            Assert.Throws<FormatException>(() => PqAddress.Decode(test));
        }
    }

    private const string TestMnemonic =
        "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about";

    [Fact]
    public void Master_seed_is_HMAC_SHA512_of_the_BIP39_seed_keyed_by_Blazecoin_PQ()
    {
        // Pinned independently (Python hmac/hashlib over the well-known BIP39 seed of this
        // mnemonic, 5eb00bbd…): master_seed = HMAC-SHA512(key="Blazecoin PQ", data=seed)[0:32].
        var seed = new Mnemonic(TestMnemonic, Wordlist.English).DeriveSeed("");
        Assert.StartsWith("5eb00bbddcf069084889a8ab9155568165f5c453ccb85e70811aaed6f6da5fc1", Hex(seed));
        var master = PqKeyDerivation.MasterSeedFromBip39Seed(seed);
        Assert.Equal("ae7ee20a64f653c4f7363da0418f1c514b25eafe4724283129ba4d5364350d49", Hex(master));

        // ξ_0 and the resulting mainnet/regtest addresses of this wallet's PQ slot 0.
        var key0 = PqKeyDerivation.Derive(master, 0);
        Assert.Equal("1992a6498a1a4aede90808756e2460a634d7840427838b9cb13eb64ce63a8137", Hex(key0.Seed));
        Assert.Equal("038a261ebf25a4e110aa620da3d4584bb200b5fdc004ad3e91dc9ac8e76ad836", Hex(key0.KeyHash));
        Assert.Equal("BQGg8psUx4ZkSpzFwkZtAHCm7EtCqxz5fobVPMVhsx8TpNHMoM9m", key0.Address());
        Assert.Equal("TQ4owRuLyVQGcS8ZMfV47TeM6DaD8uv5u4F3axA1HRTZoPasHkaY", key0.Address(BlazecoinNetwork.Regtest));

        // The BIP39 passphrase changes the seed, hence the PQ chain too (a "25th word" wallet
        // is a different wallet for PQ keys exactly as for legacy keys).
        var trezor = PqKeyDerivation.MasterSeedFromBip39Seed(new Mnemonic(TestMnemonic, Wordlist.English).DeriveSeed("TREZOR"));
        Assert.Equal("c4908f929d4c5c8727993effb3328f368695b9d2964cd01d0280159c0b49feb2", Hex(trezor));

        // The HD wallet exposes the same chain.
        var wallet = LiteHdWallet.Restore(TestMnemonic);
        Assert.Equal("BQGg8psUx4ZkSpzFwkZtAHCm7EtCqxz5fobVPMVhsx8TpNHMoM9m", wallet.GetPqAddress(0));
        Assert.Equal(key0.KeyHash, wallet.GetPqKey(0).KeyHash);
        Assert.Equal("TQ4owRuLyVQGcS8ZMfV47TeM6DaD8uv5u4F3axA1HRTZoPasHkaY",
            LiteHdWallet.Restore(TestMnemonic, network: BlazecoinNetwork.Regtest).GetPqAddress(0));
    }

    // ── sighash ───────────────────────────────────────────────────────────────────────────

    [Fact]
    public void Every_sighash_vector_reproduces_preimage_digest_signature_and_scriptSig()
    {
        var txs = Root.GetProperty("sighash").EnumerateArray().ToList();
        Assert.Equal(3, txs.Count);
        var inputsChecked = 0;
        foreach (var t in txs)
        {
            var label = t.GetProperty("label").GetString();
            var hex = t.GetProperty("tx").GetString()!;
            var tx = ParseTx(hex);
            Assert.Equal(t.GetProperty("txid").GetString(), tx.GetHash().ToString());
            Assert.Equal(hex, tx.ToHex()); // NBitcoin round-trips the PQ scriptSigs byte-for-byte

            var prevouts = t.GetProperty("prevouts").EnumerateArray().ToList();
            Assert.Equal(tx.Inputs.Count, prevouts.Count);

            foreach (var r in t.GetProperty("inputs").EnumerateArray())
            {
                var n = r.GetProperty("input").GetInt32();
                var amount = r.GetProperty("amount").GetInt64();
                var scriptCode = Hex(r.GetProperty("scriptCode").GetString()!);
                var key = Keys.Value[r.GetProperty("key_index").GetInt32()];
                var sig = Hex(r.GetProperty("sig").GetString()!);

                Assert.Equal(prevouts[n].GetProperty("scriptPubKey").GetString(), Hex(scriptCode));
                Assert.Equal(prevouts[n].GetProperty("amount").GetInt64(), amount);
                Assert.Equal(key.ScriptPubKey, scriptCode); // key_index really owns this prevout

                if (r.TryGetProperty("preimage", out var pre))
                    Assert.True(Hex(pre.GetString()!).AsSpan().SequenceEqual(PqSigHash.Preimage(tx, n, amount, scriptCode)),
                        $"{label} input {n}: preimage differs");

                var digest = PqSigHash.Digest(tx, n, amount, scriptCode);
                Assert.True(r.GetProperty("digest").GetString() == Hex(digest), $"{label} input {n}: digest differs");

                // The vector's signature verifies under the tx context, and DETERMINISTIC
                // re-signing reproduces it byte-for-byte (no per-signature randomness).
                Assert.True(MlDsa44.Verify(key.PublicKey, digest, sig), $"{label} input {n}: vector signature does not verify");
                Assert.True(sig.AsSpan().SequenceEqual(MlDsa44.Sign(key.Private, digest)), $"{label} input {n}: re-signing is not byte-identical");

                var scriptSig = PqScript.BuildScriptSig(sig, key.KeyBlob);
                Assert.Equal(PqScript.ScriptSigLength, scriptSig.Length);
                Assert.Equal(tx.Inputs[n].ScriptSig.ToBytes(), scriptSig);
                if (r.TryGetProperty("scriptSig", out var ss))
                    Assert.Equal(ss.GetString(), Hex(scriptSig));
                var parsed = PqScript.TryParseScriptSig(scriptSig);
                Assert.NotNull(parsed);
                Assert.Equal(sig, parsed.Value.Signature);
                Assert.Equal(key.KeyBlob, parsed.Value.KeyBlob);
                inputsChecked++;
            }
        }
        Assert.Equal(1 + 2 + 26, inputsChecked);
    }

    [Fact]
    public void Signature_context_and_message_are_domain_separated()
    {
        var key = Keys.Value[0];
        var msg = SHA256.HashData("m"u8);
        var sig = MlDsa44.Sign(key.Private, msg);
        Assert.Equal(MlDsa44.SignatureLength, sig.Length);
        Assert.True(MlDsa44.Verify(key.PublicKey, msg, sig));
        Assert.False(MlDsa44.Verify(key.PublicKey, SHA256.HashData("n"u8), sig));
        Assert.False(MlDsa44.Verify(Keys.Value[1].PublicKey, msg, sig));
        Assert.False(MlDsa44.Verify(key.PublicKey, msg, sig[..^1]));
        Assert.False(MlDsa44.Verify(key.PublicKey[..^1], msg, sig));
        var flipped = (byte[])sig.Clone(); flipped[100] ^= 1;
        Assert.False(MlDsa44.Verify(key.PublicKey, msg, flipped));
    }

    // ── spend ─────────────────────────────────────────────────────────────────────────────

    [Fact]
    public void Every_spend_case_returns_exactly_its_expected_verdict()
    {
        var sighash = Root.GetProperty("sighash");
        var cases = Root.GetProperty("spend").EnumerateArray().ToList();
        Assert.Equal(29 + 10 + 1, cases.Count);
        var seen = new HashSet<PqInputVerdict>();
        foreach (var c in cases)
        {
            var label = c.GetProperty("label").GetString();
            var hex = c.TryGetProperty("tx_ref", out var tr)
                ? sighash[tr.GetInt32()].GetProperty("tx").GetString()!
                : c.GetProperty("tx").GetString()!;
            var expect = Enum.Parse<PqInputVerdict>(c.GetProperty("expect").GetString()!);
            var activated = !(c.TryGetProperty("sigversion", out var sv) && sv.GetString() == "BASE");

            var got = PqInputVerifier.Verify(hex, c.GetProperty("input").GetInt32(), c.GetProperty("amount").GetInt64(),
                Hex(c.GetProperty("scriptPubKey").GetString()!), activated);
            Assert.True(expect == got, $"{label}: expected {expect}, got {got}");
            seen.Add(got);
        }
        // Every verdict the enum can give is pinned by at least one vector.
        Assert.Equal(Enum.GetValues<PqInputVerdict>().ToHashSet(), seen);
    }

    [Fact]
    public void Verifier_refuses_a_non_P2PQH_prevout_and_a_bad_index_rather_than_guessing()
    {
        var t = Root.GetProperty("sighash")[0];
        var hex = t.GetProperty("tx").GetString()!;
        var legacy = new Key().PubKey.GetAddress(ScriptPubKeyType.Legacy, BlazecoinNetwork.Instance).ScriptPubKey.ToBytes();
        Assert.Throws<ArgumentException>(() => PqInputVerifier.Verify(hex, 0, 1, legacy, activated: true));
        Assert.Throws<ArgumentOutOfRangeException>(() => PqInputVerifier.Verify(hex, 1, 1, Keys.Value[0].ScriptPubKey, activated: true));
        Assert.Throws<ArgumentException>(() => PqInputVerifier.Verify("zz", 0, 1, Keys.Value[0].ScriptPubKey, activated: true));
    }

    // ── script shapes ─────────────────────────────────────────────────────────────────────

    [Fact]
    public void Template_recognition_is_exact()
    {
        var kh = Keys.Value[0].KeyHash;
        var good = PqScript.BuildP2pqh(kh);
        Assert.True(PqScript.IsP2pqh(good));
        Assert.Equal(kh, PqScript.TryParseP2pqh(good));

        var wrongOp = (byte[])good.Clone(); wrongOp[33] = 0xb9;    // OP_NOP10
        var wrongPush = (byte[])good.Clone(); wrongPush[0] = 0x21;
        Assert.False(PqScript.IsP2pqh(wrongOp));
        Assert.False(PqScript.IsP2pqh(wrongPush));
        Assert.False(PqScript.IsP2pqh(good[..33]));
        Assert.False(PqScript.IsP2pqh(good.Concat(new byte[] { 0x00 }).ToArray()));
        Assert.Null(PqScript.TryParseP2pqh(new Key().PubKey.Hash.ScriptPubKey.ToBytes()));
        Assert.Null(PqScript.TryParseP2pqh(ReadOnlySpan<byte>.Empty));
        Assert.Throws<ArgumentException>(() => PqScript.BuildP2pqh(new byte[31]));
    }

    [Fact]
    public void Push_only_parser_matches_the_interpreter()
    {
        // Small pushes, PUSHDATA1/2/4, OP_0, OP_1..OP_16, OP_1NEGATE are pushes …
        var script = new byte[] { 0x01, 0xaa, 0x4c, 0x01, 0xbb, 0x4d, 0x01, 0x00, 0xcc, 0x4e, 0x01, 0x00, 0x00, 0x00, 0xdd, 0x00, 0x51, 0x60, 0x4f };
        var stack = PqScript.TryParsePushOnly(script);
        Assert.NotNull(stack);
        Assert.Equal(new[] { "aa", "bb", "cc", "dd", "", "01", "10", "81" }, stack.Select(e => Hex(e)));
        // … a non-push opcode, a truncated push and OP_RESERVED are not.
        Assert.Null(PqScript.TryParsePushOnly(new byte[] { 0x01, 0xaa, 0x61 }));
        Assert.Null(PqScript.TryParsePushOnly(new byte[] { 0x4d, 0x10 }));
        Assert.Null(PqScript.TryParsePushOnly(new byte[] { 0x05, 0x01 }));
        Assert.Null(PqScript.TryParsePushOnly(new byte[] { 0x50 }));
        Assert.Empty(PqScript.TryParsePushOnly(ReadOnlySpan<byte>.Empty)!);
        Assert.Null(PqScript.TryParseScriptSig(new byte[] { 0x01, 0xaa }));
    }
}
